const DEFAULT_GITHUB_GRAPHQL_ENDPOINT = 'https://api.github.com/graphql'
const DEFAULT_GITHUB_REST_ENDPOINT = 'https://api.github.com'

export const GITHUB_GRAPHQL_ENDPOINT =
  import.meta.env.VITE_GITHUB_GRAPHQL_ENDPOINT ?? DEFAULT_GITHUB_GRAPHQL_ENDPOINT

export const GITHUB_REST_ENDPOINT = import.meta.env.VITE_GITHUB_REST_ENDPOINT ?? DEFAULT_GITHUB_REST_ENDPOINT
